name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest gpxpy numpy pandas pyproj Pillow

    - name: Run unit tests
      run: |
        python -m pytest tests/test_page_generation.py -v

    - name: Test page generation
      run: |
        python -c "from page_generation import put_tiles_in_pages, get_filled_pages; \
                   tiles = [(i, j) for i in range(30) for j in range(30)]; \
                   pages = put_tiles_in_pages(tiles, 14, 9); \
                   print(f'Generated {len(pages)} pages from {len(tiles)} tiles')"
